# Generated by Django 4.2.3 on 2023-07-28 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_log'),
    ]

    operations = [
        migrations.DeleteModel(
            name='baicsform',
        ),
        migrations.DeleteModel(
            name='information',
        ),
        migrations.DeleteModel(
            name='log',
        ),
    ]
