# Generated by Django 4.2.3 on 2023-07-28 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0003_delete_baicsform_delete_information_delete_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='descri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images/')),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.IntegerField()),
                ('product_descrition', models.CharField(max_length=100)),
            ],
        ),
    ]
