# Generated by Django 4.2.3 on 2023-07-31 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_signin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='signin',
            new_name='createacc',
        ),
    ]
