# Generated by Django 4.2.3 on 2023-07-31 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_rename_signin_createacc'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=10)),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.descri')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.createacc')),
            ],
        ),
    ]
